import "./globals.css";
import { Nav } from "./components/Nav";
import Provider from "./prvider";

export const metadata = {
  title: "يمتاز",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={` bg-[#f9f9f9] font-sans`}>
        <Nav />
        <div className="flex justify-center">
          <Provider>
            {children}
          </Provider>
        </div>
      </body>
    </html>
  );
}
