import "./globals.css";
import { Nav } from "./components/Nav";
import Providers from "../providers"

export const metadata = {
  title: "يمتاز | مكانك الامن لحجز رحلاتك",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={`bg-[#f9f9f9] font-sans`}>
        <Nav />
        <div className="flex justify-center">
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
